### ISSUE TITLE
compile error with intel/2015.483 due  to boost

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/mpqc#39] opened 2015-09-09 03:54 UTC
/hyades/home/valeev/pchong/Development/source/mpqc/src/lib/util/misc/xmlwriter.h(359): error: no instance of overloaded function "sc::write_xml" matches the argument list
            argument types are: (std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int>>>, boost::property_tree::ptree, const sc::XMLWriter)
          return write_xml(std::forward<T>(obj), parent, *this);
                 ^
          detected during:
            instantiation of "boost::property_tree::ptree &sc::XMLWriter::write_to_xml(T &&, boost::property_tree::ptree &) const [with T=std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int>>> &]" at line 318
            instantiation of "boost::property_tree::ptree &sc::XMLWriter::insert_child(boost::property_tree::ptree &, T &&, std::string) const [with T=std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int>>>]" at line 305 of "/hyades/home/valeev/pchong/Development/source/mpqc/src/lib/chemistry/qc/scf/cadf/statistics.cc"

compilation aborted for /hyades/home/valeev/pchong/Development/source/mpqc/src/lib/chemistry/qc/scf/cadf/statistics.cc (code 2)
make[2]: *** [src/lib/chemistry/qc/scf/CMakeFiles/scf.dir/cadf/statistics.cc.o] Error 2
make[1]: *** [src/lib/chemistry/qc/scf/CMakeFiles/scf.dir/all] Error 2
make: *** [all] Error 2

**Comment by pchong90** [comment] 2015-09-09 20:45
update:
gcc/5.1.0 works fine, the config file
```
PROJECT=mpqc

module purge
module load gcc/5.1.0
module load cmake
module load eigen
module load mvapich/2.1
module load libint/2.1.0


SOURCE_DIR="${HOME}/Development/source/${PROJECT}"
INSTALL_DIR="${HOME}/Development/install/${PROJECT}_gcc"


source /hyades/home/software/intel/parallel_studio_xe_2013/composer_xe_2013_sp1.3.174/mkl/bin/mklvars.sh intel64 lp64

cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_CXX_FLAGS="-std=c++11" \
       CC=gcc CXX=g++ \
      -DMPI_C_COMPILER=mpicc \
      -DMPI_CXX_COMPILER=mpicxx \
      -DCMAKE_PREFIX_PATH="hyades/home/software/intel/parallel_studio_xe_2013/composer_xe_2015.3.187/mkl/" \
      -DTILEDARRAY_DIR=$HOME/Development/install/tiledarray_gcc \
      -DLIBINT=${LIBINT_DIR} \
      -DBOOST=/hyades/home/valeev/pchong/Development/install/boost/ \
      -DMPQC_NEW_FEATURES=1 \
      -DEIGEN_INCLUDE_DIR=${EIGEN_INC} \
      ${SOURCE_DIR}
```

intel/2015.483 throws error like in previous comment, config file
```
PROJECT=mpqc
MPI_VENDOR=intel
BLAS_VENDOR=mkl

# Set directory variables
SOURCE_DIR="${HOME}/Development/source/${PROJECT}"
INSTALL_DIR="${HOME}/Development/install/${PROJECT}_intel"


module purge
module load intel/2015.483
module load cmake
module load eigen
module load boost
module load libint/2.1.0

echo ${LIBINT_DIR}

cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_CXX_FLAGS="-std=c++11" \
       CC=icc CXX=icpc \
      -DMPI_C_COMPILER=mpiicc \
      -DMPI_CXX_COMPILER=mpiicpc \
      -DCMAKE_PREFIX_PATH="/hyades/home/software/intel/parallel_studio_xe_2013/impi/5.0.3.048/intel64/;/hyades/home/software/intel/parallel_studio_xe_2013/composer_xe_2015.3.187/mkl/" \
      -DTILEDARRAY_DIR=$HOME/Development/install/tiledarray_intel \
      -DLIBINT=${LIBINT_DIR} \
      -DBOOST=/hyades/home/valeev/pchong/Development/install/boost/ \
      -DMPQC_NEW_FEATURES=1 \
      -DEIGEN_INCLUDE_DIR=${EIGEN_INC} \
      ${SOURCE_DIR}
```

**Comment by evaleev** [comment] 2016-02-18 14:25
can't reproduce, won't fix

**Closed by evaleev** 2016-02-18 14:25 UTC
Labels: wontfix
